name: Node.JS CI/CD

on:
  push:
    branches: [main]


jobs:

  # Heavily modified deploy job to fit render.com
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings
